version: "3.3"

services:
  postgres:
    restart: always
    container_name: postgres
    build:
      context: .
      dockerfile: postgres/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"